export enum EConfirmRegisterError {
  CANNOT_FIND_VERIFICATION_CODE = 'CANNOT_FIND_VERIFICATION_CODE',
  REGISTER_CODE_EXPIRED = 'REGISTER_CODE_EXPIRED',
  CANNOT_FIND_USER = 'CANNOT_FIND_USER'
}

export enum EErrorDetail {
  CANNOT_FIND_VERIFICATION_CODE = 'CANNOT_FIND_VERIFICATION_CODE',
  REGISTER_CODE_EXPIRED = 'REGISTER_CODE_EXPIRED',
  CANNOT_FIND_USER = 'CANNOT_FIND_USER'
}
