export enum EnumPermission {
  // JOB
  CREATE_JOB = 'CREATE_JOB',
  UPDATE_JOB = 'UPDATE_JOB',
  MANAGE_SKILL = 'MANAGE_SKILL',
  UPDATE_HIRING_TEAM = 'UPDATE_HIRING_TEAM',
  ADD_CANDIDATE = 'ADD_CANDIDATE',

  // CANDIDATE
  MANAGE_TALENT_POOL = 'MANAGE_TALENT_POOL',
  MOVE_CANDIDATE = 'MOVE_CANDIDATE',
  DELETE_CANDIDATE = 'MOVE_CANDIDATE',
  MANAGE_INTERVIEW = 'MANAGE_INTERVIEW',
  UPDATE_FOLLOWERS = 'UPDATE_FOLLOWERS',
  UPDATE_OWNER = 'UPDATE_OWNER',
  RATE_CANDIDATE = 'RATE_CANDIDATE',

  // EMPLOYEE
  CREATE_EMPLOYEE = 'CREATE_EMPLOYEE',
  DELETE_EMPLOYEE = 'DELETE_EMPLOYEE',
  VIEW_PERSONAL_SECTION = 'VIEW_PERSONAL_SECTION',
  VIEW_JOB_SECTION = 'VIEW_JOB_SECTION',
  VIEW_EMPLOYMENT_EDUCATION_SECTION = 'VIEW_EMPLOYMENT_EDUCATION_SECTION',
  VIEW_TIME_OFF_BALANCE = 'VIEW_TIME_OFF_BALANCE',

  EDIT_PERSONAL_SECTION = 'EDIT_PERSONAL_SECTION',
  EDIT_JOB_SECTION = 'EDIT_JOB_SECTION',
  EDIT_EMPLOYMENT_EDUCATION_SECTION = 'EDIT_EMPLOYMENT_EDUCATION_SECTION',

  // TEAM
  CREATE_TEAM = 'CREATE_TEAM',

  // TASK
  MANAGE_TASK = 'MANAGE_TASK',

  // GENERAL
  SHOW_ORG_CHART = 'SHOW_ORG_CHART',

  // SETTING
  MANAGE_GENERAL_SETTING = 'MANAGE_GENERAL_SETTING', // Company / Locations / Departments / Sub Departments / Teams / Business Units / Preferences / Email
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_TIME_OFF = 'MANAGE_TIME_OFF' //Policy/ Timeoff type/ Holiday Calendar/ Workweek/ Import Timeoff balance/ Export
}
