export enum EnumUserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum EnumUserType {
  NORMAL = 'NORMAL',
  OPERATE = 'OPERATE',
  ADMIN = 'INTERNSHIP'
}

export enum EPermission {
  KYC_REVIEW = 'KYC_REVIEW',
  DISABLE_USER = 'DISABLE_USER',
  ENABLE_USER = 'ENABLE_USER',
  EDIT_USER = 'EDIT_USER',
  VIEW_USERS = 'VIEW_USERS',
  EDIT_RATE = 'EDIT_RATE',
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',
  VIEW_WITHDRAW_PROGRESS = 'VIEW_WITHDRAW_PROGRESS',
  REVIEW_WITHDRAW = 'REVIEW_WITHDRAW',
  CHANGE_SERVER_CONFIG = 'CHANGE_SERVER_CONFIG',
  VIEW_REPORT = 'VIEW_REPORT',
  ENABLE_PARTNER = 'ENABLE_PARTNER',
  UPDATE_GAME_SETTING = 'UPDATE_GAME_SETTING',
  SET_RANK = 'SET_RANK',
  VIEW_ORDERS = 'VIEW_ORDERS',
  LEADER = 'LEADER',
  SIGN = 'SIGN',
  EDIT = 'EDIT',
  VIEW = 'VIEW',
}

export enum EAuthProvider {
  EMAIL = 'EMAIL',
  GOOGLE = 'GOOGLE',
  FACEBOOK = 'FACEBOOK',
  APPLE = 'APPLE'
}

export enum EAccountType {
  
}