export enum EErrorFile {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  USER_ID_NOT_MATCH = 'USER_ID_NOT_MATCH',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND'
}

export enum EErrorDetail {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  USER_ID_NOT_MATCH = 'USER_ID_NOT_MATCH',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND'
}
