export enum ECategoriesType {
    ESSENTIAL_NEED = 'ESSENTIAL_NEED',
    PERSONAL_WANTS = 'PERSONAL_WANTS',
    SAVING_AND_INVESTMENT = 'SAVING_AND_INVESTMENT',
    FAMILY_AND_GIVING = 'FAMILY_AND_GIVING',
    OTHER = 'OTHER'
}