export enum EErrorExpenses {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  CANNOT_FIND_BUDGET = 'CANNOT_FIND_BUDGET',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_BUDGET_ID = 'INVALID_BUDGET_ID'
}

export enum EErrorDetail {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  CANNOT_FIND_BUDGET = 'CANNOT_FIND_BUDGET',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_BUDGET_ID = 'INVALID_BUDGET_ID'
}
