export enum EErrorExpenses {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  CANNOT_FIND_BUDGET = 'CANNOT_FIND_BUDGET'
}

export enum EErrorDetail {
  CANNOT_FIND_USER = 'CANNOT_FIND_USER',
  CANNOT_FIND_BUDGET = 'CANNOT_FIND_BUDGET'
}
